### PR TITLE
ProductCatalog release name is limited to 7 characters

### PR DESCRIPTION
**Pull request by ferenc-hechler**
This PR fixes issue #306 

The port names of all v1beta3 components in the testData folder were changed, 
so that the release name is no longer contained.
The release name can now be 32 characters.

### CODE REVIEW

**Comment by ferenc-hechler** [comment]
Tests are failing (locally executed tests had no errors...)

https://reports.cucumber.io/reports/bb7313a2-8781-4b5a-9f57-1ab9e9d410e2

image

Maybe it is related to the preinstalled components which come from the repo and not from the oda-canvas github repo.

**Comment by ferenc-hechler** [comment]
I rerun the tests without having changed anything and now the tests are green:
https://reports.cucumber.io/reports/f4ffcdb1-e267-4e47-8ecd-1a116e641f8e

**Comment by thomo** [comment]
Found further locations:
- `feature-definition-and-test-kit/testData/productcatalog-enhanced-v1beta3/templates/deployment-promotionmanagementapi.yaml` line 43
- `feature-definition-and-test-kit/testData/productcatalog-enhanced-v1beta3/templates/service-promotionmanagementapi.yaml` line 12
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/deployment-metricsapi.yaml` line 29
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/deployment-mongodb.yaml` line 23
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/deployment-partyroleapi.yaml`
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/deployment-productcatalogapi.yaml`
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/service-mongodb.yaml`
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/service-partyroleapi.yaml`
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/service-productcatalogapi.yaml`
- `feature-definition-and-test-kit/testData/productcatalog-v1alpha4/templates/service-registerallevents.yaml`

Also in `feature-definition-and-test-kit/testData/productcatalog-v1beta2/templates` and `feature-definition-and-test-kit/testData/productinventory-v1beta3/templates`

**Comment by ferenc-hechler** [comment]
I only changed the yamls for the v1beta3 components, because these are the ones which are further developed.
v1alpha4 and v1beta2 are left unchanged.

**Review by LesterThomas — APPROVED** [review]
Looks good to me

**Pull request merged**
