### PR TITLE
311 documentation minor documentation bug fixes

### LINKED ISSUE #311: Documentation: Minor documentation bug fixes
## Description

The [Documentation Website](https://tmforum-oda.github.io/oda-ca-docs/) is built automatically using [Sphinx](https://tmforum-oda.github.io/oda-ca-docs/docs/DocumentationProcess.html). It automatically checks any cross-references. It has identified a number of missing links/invalid headers. This issue is to fox those minor bugs in the documentation.

### PR DESCRIPTION
**Pull request by LesterThomas**
Closes #311 

It fixes some of the renaming of Use-cases and changes some URLs to use absolute instead of relative paths.

### CODE REVIEW

**Comment by brian-burton** [comment]
@LesterThomas, looks good, but the internal links are not consistent.

For example we link to other parts of the repo [here](https://github.com/tmforum-oda/oda-canvas/blob/809b535ea80fc94b8521f86c707578480bf4dc97/Canvas-design.md?plain=1#L33), [here](https://github.com/tmforum-oda/oda-canvas/blob/809b535ea80fc94b8521f86c707578480bf4dc97/Canvas-design.md?plain=1#L34) and [here](https://github.com/tmforum-oda/oda-canvas/blob/809b535ea80fc94b8521f86c707578480bf4dc97/README.md?plain=1#L44) but one is a relative link, one is an absolute link to `tree/master` and one is an absolute link to `blob/master`.

**Comment by LesterThomas** [comment]
> @LesterThomas, looks good, but the internal links are not consistent.
> 
> For example we link to other parts of the repo [here](https://github.com/tmforum-oda/oda-canvas/blob/809b535ea80fc94b8521f86c707578480bf4dc97/Canvas-design.md?plain=1#L33), [here](https://github.com/tmforum-oda/oda-canvas/blob/809b535ea80fc94b8521f86c707578480bf4dc97/Canvas-design.md?plain=1#L34) and [here](https://github.com/tmforum-oda/oda-canvas/blob/809b535ea80fc94b8521f86c707578480bf4dc97/README.md?plain=1#L44) but one is a relative link, one is an absolute link to `tree/master` and one is an absolute link to `blob/master`.

So far, I have only responded to the incorrect links that the Sphinx documentation builder was highlighting (hence the remaining inconsistencies). I'll do some more changes to improve the consistency.

**Comment by LesterThomas** [comment]
I've updated to improve the relative/absolute link consistency. There are still some absolute links, for when the target document isn't part of the documentation website (for example when linking to `values.yaml` files - the sphinx documentation requires these to be absolute links.

**Review by brian-burton — APPROVED** [review]
LGTM

**Pull request merged**
