### PR TITLE
Odaa 98 automate docker builds

### PR DESCRIPTION
**Pull request by ferenc-hechler**

### CODE REVIEW

**Comment by ferenc-hechler** [comment]
We have two contradicting checks:

**trigger_test** needs the prerelease images to exist for making the canvas deployment.
On the other hand, we do not want to bring prerelease images into production.
So, the **check that PRs do not contain prereleaseSuffixes** fails now, but the trigger_test can now run.

If the trigger_test (BDD) is successful, we can remove the "odaa98" prerelease suffixes in the chart/oda-canvas/values.yaml, then the Check will succeed, but the tests will fail.

We have to implement a smart solution for handling this in the near future.

Unfortunately today I have no time to join the sprint review. 
For reviewing this pullrequst please also look at the documentation:
https://github.com/tmforum-oda/oda-canvas/blob/odaa-98-automate-docker-builds/docs/developer/work-with-dockerimages.md

**Comment by ferenc-hechler** [comment]
Now the trigger_test were successful:
image

I will remove the odaa98 prerelease suffix, then the PR is ready for merging.

**Comment by ferenc-hechler** [comment]
@anshulkumar-tmf configured the secrets in the GitHub repo and I changed the code, so that now the secrets are used. 

For testing the secrets I reconfigured the prerelease suffix again to odaa98, so the "trigger_test" should be successful, but it failed with the following error message:

image

There were no functional change in the PR.
So, I assume that the changes were in the reference-example-components repository.

I remember that @RJ-acc had some issues with typo of apiType and the error points into this direction.

**Comment by ferenc-hechler** [comment]
After syncing with the master branch I get 18 errors, all about "required Value: apiType"

image

Looks like a green hook on "trigger_test" shows, that the tests were executed without crashing.
But it does not respect the test result. Failing tests are not detected.
Looking at the published Cucumber URL I can see, that there are 18 errors as mentioned above:

https://reports.cucumber.io/reports/c1c597fa-a7aa-436e-9a92-e13b3dfc3aad

**Review by LesterThomas — APPROVED** [review]
This looks good to me. I suggest you should take the team through the new automated docker-build process to ensure everyone understands it.

**Comment by ferenc-hechler** [comment]
After merging the latest changes from "master" branch, the tests are now green:
https://reports.cucumber.io/reports/5b2abe8d-ecd5-4361-aa53-d7aa55c9224b

**Comment by LesterThomas** [comment]
Shall I merge into the main branch?

**Comment by ferenc-hechler** [comment]
I was awaiting approval from the other reviewers.
Before merging I have to unset the prereleaseSuffixes in the values.yaml.
This will fix the failing check (and at the same time break the BDD tests)

**Pull request merged**
