### PR TITLE
Odaa 114: Fix BDD Tests

### PR DESCRIPTION
**Pull request by ferenc-hechler**
For details see https://projects.tmforum.org/jira/browse/ODAA-114

this PR contains two things:

* bugfix for exception thrown in DependentAPI-Operator if an API cr does not have an implementation status
* create a fake API for specification TMF632, which is listed as dependent API in the ctk, pc and pi component

The two failing BDD tests (UC003-F004 and UC005-F001)  are now green:

https://reports.cucumber.io/reports/cd81f8bc-a852-48a7-bccf-3bcc9671f4cc

grafik

Cucumber report generated from the github actions: https://reports.cucumber.io/reports/0f1c98db-9a89-4c54-bf41-5843237373e6

### CODE REVIEW

**Comment by ferenc-hechler** [comment]
@aankursarkar: I can not assign you as reviewer, 
but could you please take a look at the change in your code for dependentApiSimpleOperator.py?

**Comment by aankursarkar** [comment]
> @aankursarkar: I can not assign you as reviewer, but could you please take a look at the change in your code for dependentApiSimpleOperator.py?

@ferenc-hechler : I have reviewed the changes in dependentApiSimpleOperator.py, and they seem correct to me.

**Comment by LesterThomas** [comment]
@ferenc-hechler @ajayaggarwal03 @Suyash7774 - I've removed the dependent APIs from all the test component packages so we won't need any workarounds to manage dependencies.

We will need to create some specific BDD scenarios for testing dependencies and I've created an additional test component `productcatalog-dependendent-API-v1beta3` that does have a dependent API.

I've also added some additional logging so that any failed BDD scenarios will log the ODA Controller pod for troubleshooting.

**Comment by ferenc-hechler** [comment]
@ajayaggarwal03 can you rerun the BDD tests and, if there are no errors, give an approval?
Then we can merge this PR.

**Comment by ferenc-hechler** [comment]
Aligned with @ajayaggarwal03 and copied the [trigger_tests.yaml](https://github.com/tmforum-oda/oda-canvas/blob/odaa-114-fix-tests/.github/workflows/trigger_tests.yml) from the "odaa-114-fix-tests" branch.
This started triggered the GitHub Action the run the BDD tests.

The result was successful:
https://reports.cucumber.io/reports/fba68c20-b49a-46ef-8d83-4d87afee85fa

image

**Pull request merged**
