### PR TITLE
Some small changes and reformattings 

### LINKED ISSUE #148: Some small changes and reformattings
## Modifications

- note about clone git repo
- use triple backticks instead of quadruple backticks
- some reformattings

### PR DESCRIPTION
**Pull request by thomo**
- add note about clone git repo
- use triple backticks instead of quadruple backticks
- reformattings

closes #148

### CODE REVIEW

**Comment by gusjer** [comment]
@LesterThomas, it seems like we have encountered an issue. Although we don't want to close issue #140 when someone adds documentation improvements, our workflow requires us to close the issue to merge back to the main branch. How do you suggest we proceed?

**Comment by thomo** [comment]
Would it be a solution that I create another issue for my changes and link this in the PR? I could also mention #140 in the new issue.

**Comment by LesterThomas** [comment]
> @gusjer Would it be a solution that I create another issue for my changes and link this in the PR? I could also mention #140 in the new issue.

Yes - I think this is the best approach

**Review by LesterThomas — APPROVED** [review]
Many thanks for these improvements.

**Pull request merged**
