### PR TITLE
[skip tests] 303 Update Usecase 007 description - configure Dependent APIs for CanvasInfo

### PR DESCRIPTION
**Pull request by LesterThomas**
This is updating the Usecase 007 to reflect the latest design of the Dependent APIs and CanvasInfo service.

### CODE REVIEW

**Comment by ferenc-hechler** [comment]
The sequence diagram is not shown in the GitHub viewer, 
so I add it here a screenshot as base for reviewing:

**Comment by ferenc-hechler** [comment]
In the sequence diagram the DependentAPI-Operator is directly communicating with the IdentityManagementSystem.

image

I see some overlap of API-Gateway and IdentityProvider responsibilities here.

Maybe the DependetAPI-Operator could start a request against the Identity-Config-Operator, 
which knows the concrete IdentityManagementSystem.

Otherwise the DependentAPI-Operator needs different implementations for different IdentityManagementSystems.

But I have no clear view, how the responsibilities for Access-Control is distributed.
That´s the reason, why we started implementing the DependentAPI-Operator without credentials.   :-)

**Comment by LesterThomas** [comment]
> In the sequence diagram the DependentAPI-Operator is directly communicating with the IdentityManagementSystem.
> 
> image
> 
> I see some overlap of API-Gateway and IdentityProvider responsibilities here.
> 
> Maybe the DependetAPI-Operator could start a request against the Identity-Config-Operator, which knows the concrete IdentityManagementSystem.
> 
> Otherwise the DependentAPI-Operator needs different implementations for different IdentityManagementSystems.
> 
> But I have no clear view, how the responsibilities for Access-Control is distributed. That´s the reason, why we started implementing the DependentAPI-Operator without credentials. :-)

Good comment. @brian-burton - did you have a view of how other operators should interface to the Identity Management Solution?

**Comment by LesterThomas** [comment]
I have updated the sequence diagram to reflect @brian-burton proposal: The IdentityConfigOperator now listens to create/update events on the DependentAPI, so that it can configure the Identity Management System.

image

**Comment by ferenc-hechler** [comment]
> I have updated the sequence diagram to reflect @brian-burton proposal: 
> The IdentityConfigOperator now listens to create/update events on the DependentAPI, 
> so that it can configure the Identity Management System.

Instead of this, the IdentityConfigOperator could register as listener to the Canvas-Info-Service 
and react on newly created Service-Entries in state "inactive".
After provisioning it can set the state to "active

**Comment by ferenc-hechler** [comment]
added `[skip tests]` to the PR title to suppress running the BDD tests on Doc-Only changes.

**Comment by LesterThomas** [comment]
@ferenc-hechler - I've updated to listen to Canvas.Info service as per your suggestion.

**Pull request merged**
