### PR TITLE
[wip] feat/exposedapi crd

### PR DESCRIPTION
**Pull request by OmidTahouri**
For #163

### CODE REVIEW

**Comment by brian-burton** [comment]
Hi @OmidTahouri , the model looks good to me, but can we change the keys to camelCase, please?

**Comment by OmidTahouri** [comment]
@LesterThomas @brian-burton what should happen in the case that one API GW implementation/vendor supports a feature or property in the CRD that the other does not?

**Comment by LesterThomas** [comment]
> @LesterThomas @brian-burton what should happen in the case that one API GW implementation/vendor supports a feature or property in the CRD that the other does not?

The Canvas design allows for certain features to be optional and so the scenario you describe above will happen. Our plan is for the Canvas Compliance Test Kit (CTK) to test for all these features and provide a report making the implementation transparent. A CSP will be able to decide which features are important to themselves and have the data from the CTK to inform this decision.

**Comment by brian-burton** [comment]
@OmidTahouri , the PR has conflicts. Please can you resolve them, then I can approve.

**Review by LesterThomas — APPROVED** [review]
Looks good to me

**Pull request merged**
