### PR TITLE
#302 Remove "-dapi-" infix from DependentAPI custom resource names

### PR DESCRIPTION
**Pull request by ferenc-hechler**
Component Operator was modified to not add the "-dapi-" infix when creating custom resources.
Details see #302

### CODE REVIEW

**Comment by ferenc-hechler** [comment]
BDD Test are failing waiting for the old name of the dependentapi.

image

will fix this.

**Comment by ferenc-hechler** [comment]
Tests are now green:
https://reports.cucumber.io/reports/2381c639-c773-4d8d-821a-a76c5bedf6d9

**Comment by thomo** [comment]
I perform a search on file base in the repo and found a lot of artefacts which still contains the infix '-dapi-', e.g. 

```
source/operators/componentOperator/test/testdata_DEPAPI/UPDATE_dependentapi_ready.json
95:             "name": "prodcat-productcatalogmanagement-dapi-party",
117:                    "url": "http://dummy.url/prodcat-productcatalogmanagement-dapi-party"
```
I assume these locations also need to adjust so that the corresponding "unit tests" pass. unfortunately I do not found a description how to run these unit tests.

**Comment by ferenc-hechler** [comment]
> I assume these locations also need to adjust so that the corresponding "unit tests" pass. 

I adjusted the test data, so it matches the current naming scheme.

> unfortunately I do not found a description how to run these unit tests.

Yes, these are manual tests, which I run locally. There are currently no Unit-Tests. I left them there, to have a template for running similair manual tests.

**Review by thomo — APPROVED** [review]
Looks good

**Pull request merged**
