### PR TITLE
289 Canvas-Info service is filled with endpoints retrieved in DependentAPI Operator

### PR DESCRIPTION
**Pull request by ferenc-hechler**
GitHub Issue #289 : DependentAPI Operator adds discovered service endpoints info the Service-Inventory accessible under info.canvas.svc.cluster.local.
GitHub Issue #338 : Executing and publishing Unit-Tests in Docker build is now possible.

### CODE REVIEW

**Comment by LesterThomas** [comment]
I have tested this locally by:

1. Deploying a ProductCatalog component to act as the downstream ProductCatalog with name `wholesale-catalog`
2. Deploying a second ProductCatalog component with name `federated-catalog`. This declares a dependency for a `downstreamproductcatalog`.
3. The `tmforumodacanvas/dependentapi-simple-operator:0.2.3-issue289b` microservice successfully created a Canvas Info record in the Service Inventory at `http://info.canvas.svc.cluster.local/tmf-api/serviceInventoryManagement/v5`. I manually checked this by querying the Service Inventory. It also updated the DependentAPI record to show this dependency had been met.
4. I added a `catalog` record to the `wholesale-catalog` and then queried the 'catalog' API on the `federated-catalog` component - the API call successfully returned the  `catalog` record from the `wholesale-catalog`.

So the base scenario works :)

**Comment by ferenc-hechler** [comment]
> the Service Inventory at `http://info.canvas.svc.cluster.local/tmf-api/serviceInventoryManagement/v5`
I wanted to change this to http://info.canvas.svc.cluster.local without any path. So the service functions are then available as http://info.canvas.svc.cluster.local/service

**Review by LesterThomas — APPROVED** [review]
Looks good to me!

This is the base DependentAPI use case working. There are a couple of additional features that we should raise as separate issues:

* The DependentAPI operator should be able to handle more than 1 valid API for a given dependency. I propose the status field should be an array of matching APIs.
* It would be good if we could think of a simple way to approve the dependencies. i.e the operator finding matching APIs and some SRE team activity to approve each dependency.
* We need to add the authentication.

**Comment by LesterThomas** [comment]
There is a complimentary reference component that integrates with this Canvas.Info service:
https://github.com/tmforum-oda/reference-example-components/releases/tag/productcatalog-1.2.2

**Pull request merged**
